spring:
  application:
    name: mscloudgateway
  cloud:
    gateway:
      locator:
        enabled: true
        lower-case-service-id: true

server:
    port: 18080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/