spring:
  application:
    name: mscartoes
  rabbitmq:
    host: localhost
    port: 5673
    username: guest
    password: guest
    virtual-host: /


server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

mq:
  queues:
    emissao-cartoes: emissao-cartoes